export const environment = {
    production: true,
    seguridadApi: 'https://api.corporativo.grupofarsiman.io/production/seguridad/farsiman-seguridad-corporativa-api',
    productosGraph: 'https://web-server-iis.dc2.grupofarsiman.io/Farmacia-Ecommerce-Mestros-Productos-Api/Graph/?query={@query}',
    productosApi: 'https://web-server-iis.dc2.grupofarsiman.io/Farmacia-Ecommerce-Mestros-Productos-Api/',
    productosMaestrosApi: 'https://apps.grupofarsiman.com:3003/',
    reembolsosApi: 'https://farmaciasiman.site:1201/gt/reembolso_api/',
    graphApi: 'http://apps.grupofarsiman.com:3003/graphql',
    ecommerceApi: 'https://api.farmacia.grupofarsiman.io/production/gt/super-siman/farmacia/ecommerce-admin',
    ecommerceReportesApi: 'https://api.farmacia.grupofarsiman.io/production/hn/super-siman/ecommerce/ecommerce-reports-api',
    inventarioImpulso: 'http://10.0.0.3/gt/productosimpulsados/',
    mercadeoGraph: 'http://apps.grupofarsiman.com:3005/gt/graphql',
    productosEntrenamiento:'https://api.farmacia.grupofarsiman.io/gt/production/entrenamiento/productos-api',
    planimetriaApi: '',
    configuracionesApi: 'https://api.farmacia.grupofarsiman.io/gt/production/maestros/configuracionesfarmacia',
    distribuidoresApi: 'https://apps.grupofarsiman.com:3039/gt',
    comunicadoCreditoApi: 'https://api.farmacia.grupofarsiman.io/gt/production/creditos-cobros/comunicados-api',
    ecommerceCampañasApi: 'https://api.farmacia.grupofarsiman.io/gt/production/mercadeo/notificaciones-push',
    ecommerceBuscadorApi: 'https://apps.grupofarsiman.com:3019/gt',
    ecommerceUsuariosApi: 'https://usuarios-api.ecommerce.grupofarsiman.io/gt',
    UrlApiFarmaciaSimanCom: 'https://webmail.farmaciasiman.com/gt/Farm0acia-Ecommerce-General-Api',
    ApiProductosImagenes: 'https://d2wuoo4cuot0vy.cloudfront.net/gt',
    maestrosFarmaciaApi: 'https://api.farmacia.grupofarsiman.io/farmacia/maestros-farmacia-api',
    recompraConfiguracionProductos: 'https://api.farmacia.grupofarsiman.io/production/hn/super-siman/ecommerce/recompra-configuraciones-api/gt',
    farsimanProducts: "https://api.farmacia.grupofarsiman.io/gt/farmacia/products-api/",
    cuponDigital: 'https://api.farmacia.grupofarsiman.io/gt/production/farmacia/mercadeo-cupones/api',
    mercadeoApi: 'https://api.farmacia.grupofarsiman.io/gt/production/mercadeo/mercadeo-api/api',
    experienciaUsuarioAssets: "https://assets.farmaciasiman.com/gt/public/imagenesExperienciaUsuario",
    analisisClinicoApi: "https://api.farmacia.grupofarsiman.io/production/farmacia/analisis-clinicos-api",
    ecommerceArchivosMultimedia: "https://api.farmacia.grupofarsiman.io/production/farmacia/ecommerce/multimedia-api",
    seguridadCorporativaAdmin: "https://api.corporativo.grupofarsiman.io/production/hn/corporativo/seguridad/seguridad-corporativa-admin-api",
    conserjesApi: 'https://api.farmacia.grupofarsiman.io/sad/conserjes-appmovil',
    conserjesRealtimeApi: 'https://api.farmacia.grupofarsiman.io/sad/conserjes-appmovil-realtime',
    inventarioRemotosApi: "https://api.farmacia.grupofarsiman.io/production/hn/super-siman/farmacia/inventario-remoto-api",
    stickersApi: 'https://api.farmacia.grupofarsiman.io/production/hn/super-siman/farmacia/stickers-web-api'
  };
